apiVersion: v1
kind: Service
metadata:
  name: cv-onepage-service
  namespace: default
  labels:
    app: cv-onepage
spec:
  type: NodePort
  selector:
    app: cv-onepage
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  sessionAffinity: None
